name: build
on: [workflow_dispatch]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: integration-runner/package-lock.json
          node-version: 22.1
          cache: npm
      - name: install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt --upgrade
          maturin build --release
          pip install $(find ./target/wheels/*.whl)
          cd integration-runner
          npm i
      - name: build
        shell: bash
        run: |
          pyinstaller main.py --onefile --name=liquidWeb-cli -i "NONE"
          pyinstaller framereceiver.py --onefile --name=frame-receiver -i "NONE"
          pyinstaller hardwareserver.py --name=hardware-server -i "NONE"
          cd integration-runner
          npm run package
      - name: package
        shell: bash
        run: |
          mkdir dist/modules
          mv dist/frame-receiver dist/modules/
          mv dist/hardware-server/ dist/modules/
          mv integration-runner/out/integration-runner-linux-x64/ dist/modules/
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: dist/*